FROM gradle:7.6-jdk17 AS build
WORKDIR /app
COPY build.gradle settings.gradle ./
COPY customer-service/build.gradle ./customer-service/
COPY common/build.gradle ./common/
COPY customer-service/src ./customer-service/src
COPY common/src ./common/src
RUN gradle :customer-service:build -x test

FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/customer-service/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]

